const matchReports=window.FindItAlgorithms.findMatches;
const STORAGE_KEY='findit-reports-v1';
const demoReports=[
 {id:'r1',type:'lost',title:'Black wireless earphones',category:'Electronics',color:'Black',location:'Central Library',date:'2026-09-12',time:'11:30',contact:'Aarav',contactDetail:'aarav@example.com',description:'Small black Bluetooth earphones in a charging case.',status:'Open'},
 {id:'r2',type:'found',title:'Black Bluetooth earbuds',category:'Electronics',color:'Black',location:'Central Library',date:'2026-09-12',time:'12:00',contact:'Meera',contactDetail:'meera@example.com',description:'Black wireless earbuds found near the reading tables.',status:'Possible Match'},
 {id:'r3',type:'lost',title:'Blue identity card',category:'Identity card',color:'Blue',location:'Block A corridor',date:'2026-09-10',time:'09:15',contact:'Rohan',contactDetail:'rohan@example.com',description:'College identity card in a transparent blue sleeve.',status:'Open'},
 {id:'r4',type:'found',title:'ID card in blue sleeve',category:'Identity card',color:'Blue',location:'Block A corridor',date:'2026-09-10',time:'10:00',contact:'Nisha',contactDetail:'nisha@example.com',description:'Student ID card found outside the first year classroom.',status:'Possible Match'},
 {id:'r5',type:'lost',title:'Calculus notebook',category:'Books & stationery',color:'Red',location:'Canteen',date:'2026-09-08',time:'13:00',contact:'Kabir',contactDetail:'kabir@example.com',description:'Red notebook with handwritten calculus notes.',status:'Open'}
];
let reports=loadReports();
const $=selector=>document.querySelector(selector);const $$=selector=>[...document.querySelectorAll(selector)];
function loadReports(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(saved)?saved:demoReports.map(item=>({...item}))}catch{return demoReports.map(item=>({...item}))}}
function saveReports(){localStorage.setItem(STORAGE_KEY,JSON.stringify(reports))}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]))}
function dateLabel(date){return new Date(`${date}T00:00:00`).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}
function timeLabel(time){return time?new Date(`1970-01-01T${time}`).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'}):'Time not provided'}
function navigate(view){$$('.view').forEach(el=>el.classList.toggle('active-view',el.id===view));$$('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===view));if(view==='dashboard')renderDashboard();if(view==='reports')renderReports();if(view==='matches')renderMatches();if(view==='admin')renderAdmin();window.scrollTo({top:0,behavior:'smooth'})}
function card(item){return `<article class="report-card"><div class="report-type"><span class="pill ${item.type}">${item.type==='lost'?'Lost':'Found'}</span><span class="muted">${escapeHtml(item.status)}</span></div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.description)}</p><p>📍 ${escapeHtml(item.location)} · ${escapeHtml(item.color)}</p><div class="report-meta"><span>${escapeHtml(item.category)}</span><span>${dateLabel(item.date)} · ${timeLabel(item.time)}</span></div></article>`}
function renderDashboard(){const open=reports.filter(r=>r.status!=='Returned').length;const matches=matchReports(reports).length;$('#stats').innerHTML=`<div class="stat"><strong>${reports.length}</strong><span>Total reports</span></div><div class="stat"><strong>${reports.filter(r=>r.type==='lost').length}</strong><span>Lost items</span></div><div class="stat"><strong>${reports.filter(r=>r.type==='found').length}</strong><span>Found items</span></div><div class="stat"><strong>${open}</strong><span>Still active</span></div>`;$('#recentReports').innerHTML=reports.slice().reverse().slice(0,3).map(card).join('')||'<div class="empty">No reports yet.</div>';$('#matchBadge').textContent=matches}
function renderReports(){const query=$('#searchInput').value.toLowerCase().trim(),type=$('#typeFilter').value,category=$('#categoryFilter').value,status=$('#statusFilter').value;const visible=reports.filter(r=>{const haystack=`${r.title} ${r.description} ${r.color} ${r.location} ${r.category} ${r.time||''}`.toLowerCase();return(!query||haystack.includes(query))&&(type==='all'||r.type===type)&&(category==='all'||r.category===category)&&(status==='all'||r.status===status)});$('#reportList').innerHTML=visible.map(item=>`<div class="report-card"><div><span class="pill ${item.type}">${item.type==='lost'?'Lost':'Found'}</span></div><div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.description)}</p></div><div class="report-meta"><span>${escapeHtml(item.location)}<br>${dateLabel(item.date)} · ${timeLabel(item.time)}</span><span>${escapeHtml(item.status)}</span></div></div>`).join('')||'<div class="empty">No reports match those filters.</div>'}
function renderMatches(){const matches=matchReports(reports);$('#matchList').innerHTML=matches.map(match=>`<article class="match-card"><div><h3>${escapeHtml(match.lost.title)} <span class="muted">↔</span> ${escapeHtml(match.found.title)}</h3><p>Lost at ${escapeHtml(match.lost.location)} on ${dateLabel(match.lost.date)} at ${timeLabel(match.lost.time)} · Found at ${escapeHtml(match.found.location)} on ${dateLabel(match.found.date)} at ${timeLabel(match.found.time)}</p><div class="reasons">${match.reasons.map(reason=>`<span class="reason">${escapeHtml(reason)}</span>`).join('')}</div></div><div class="score">${match.score}%<small>match score</small></div></article>`).join('')||'<div class="empty">No possible matches yet. Add both a lost and a found report with a few shared details.</div>'}
function renderAdmin(){const open=reports.filter(r=>r.status!=='Returned');$('#adminCount').textContent=`${open.length} active report${open.length===1?'':'s'}`;$('#adminList').innerHTML=reports.map(item=>`<div class="admin-row"><div><strong>${escapeHtml(item.title)}</strong><small>${item.type==='lost'?'Lost':'Found'} · ${escapeHtml(item.contact)} · ${escapeHtml(item.location)}</small></div><select data-status="${item.id}">${['Open','Possible Match','Claimed','Returned'].map(status=>`<option ${item.status===status?'selected':''}>${status}</option>`).join('')}</select><button class="secondary" data-contact="${item.id}">Show contact</button></div>`).join('')||'<div class="empty">No reports.</div>'}
function toast(message){const element=$('#toast');element.textContent=message;element.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>element.classList.remove('show'),2600)}
function refresh(){renderDashboard();if($('#reports').classList.contains('active-view'))renderReports();if($('#matches').classList.contains('active-view'))renderMatches();if($('#admin').classList.contains('active-view'))renderAdmin()}
$$('[data-view]').forEach(button=>button.addEventListener('click',()=>navigate(button.dataset.view)));['searchInput','typeFilter','categoryFilter','statusFilter'].forEach(id=>$('#'+id).addEventListener('input',renderReports));
$('#reportForm').addEventListener('submit',event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));const item={...data,id:`r${Date.now()}`,status:'Open'};reports.push(item);saveReports();event.currentTarget.reset();$('#reportForm input[name="date"]').value=new Date().toISOString().slice(0,10);$('#reportForm input[name="time"]').value=new Date().toTimeString().slice(0,5);toast('Your report was published.');navigate('reports')});
$('#resetData').addEventListener('click',()=>{if(confirm('Reset this browser to the sample reports?')){reports=demoReports.map(item=>({...item}));saveReports();refresh();toast('Demo data restored.')}});
document.addEventListener('change',event=>{if(event.target.dataset.status){const item=reports.find(r=>r.id===event.target.dataset.status);item.status=event.target.value;saveReports();refresh();toast(`Status changed to ${item.status}.`)}if(event.target.id==='categoryFilter')renderReports()});
document.addEventListener('click',event=>{const id=event.target.dataset.contact;if(id){const item=reports.find(r=>r.id===id);alert(`Coordinator contact for ${item.title}:\n${item.contact} — ${item.contactDetail}`)}});
const categories=[...new Set(demoReports.map(r=>r.category))];$('#categoryFilter').insertAdjacentHTML('beforeend',categories.map(c=>`<option>${escapeHtml(c)}</option>`).join(''));$('#reportForm input[name="date"]').value=new Date().toISOString().slice(0,10);$('#reportForm input[name="time"]').value=new Date().toTimeString().slice(0,5);renderDashboard();
